version: "3"
services:
  kratos-migrate:
    image: oryd/kratos:latest-sqlite
    volumes:
      - kratos-sqlite:/var/lib/sqlite
      - ../.kratos:/etc/config/kratos
    command: -c /etc/config/kratos/.kratos.yml migrate sql -e --yes
    restart: on-failure
    networks:
      - intranet
  kratos:
    depends_on:
      - kratos-migrate
    image: oryd/kratos:latest-sqlite
    ports:
      - 4433:4433 # public
      - 4434:4434 # admin
    restart: unless-stopped
    command: serve -c /etc/config/kratos/.kratos.yml --dev
    volumes:
      - kratos-sqlite:/var/lib/sqlite
      - ../.kratos:/etc/config/kratos
    networks:
      - intranet

  hydra-migrate:
    image: oryd/hydra
    command:
      migrate sql -e --yes
    restart: on-failure
    volumes:
      - ../.hydra/.hydra.yml:/.hydra
    networks:
      - intranet

  hydra:
    depends_on:
      - hydra-migrate
    image: oryd/hydra
    ports:
      - 4444:4444 # Public port
      - 4445:4445 # Admin port
      - 5555:5555 # Port for hydra token user
    command: serve all --dangerous-force-http
    volumes:
      - ../.hydra/.hydra.yml:/.hydra
    restart: unless-stopped
    networks:
      - intranet

  hydra-postgres:
    image: postgres
    environment:
      - POSTGRES_USER=hydra
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=hydra
    networks:
      - intranet

  nginx:
    image: nginx
    depends_on:
      - kratos
    ports:
      - 4455:4455
    restart: on-failure
    networks:
      - intranet
    volumes:
      - ./.nginx/nginx.conf:/etc/nginx/conf.d/default.conf
  mailslurper:
    image: oryd/mailslurper:latest-smtps
    ports:
      - 4436:4436
      - 4437:4437
    networks:
      - intranet
  doorknob:
    image: ukonnra/wonderland-doorknob
    environment:
      - HYDRA_ADMIN_URL=http://hydra:4445
      - HYDRA_PUBLIC_URL=http://127.0.0.1:4455/.ory/hydra/public
      - KRATOS_ADMIN_URL=http://kratos:4434
      - KRATOS_PUBLIC_URL=http://127.0.0.1:4455/.ory/kratos/public
      - FRONTEND_URL=http://127.0.0.1:4455
    restart: on-failure
    depends_on:
      - kratos
      - hydra
    networks:
      - intranet
  doorknob-react:
    image: ukonnra/wonderland-doorknob-react
    environment:
      - REACT_APP_BASE_URL=http://127.0.0.1:4455
      - REACT_APP_KRATOS_PUBLIC_URL=http://127.0.0.1:4455/.ory/kratos/public
      - REACT_APP_BACKEND_URL=http://127.0.0.1:4455/api
    restart: on-failure
    depends_on:
      - doorknob
    networks:
      - intranet
networks:
  intranet:
volumes:
  kratos-sqlite:
