version: "3"
services:
  kratos-migrate:
    image: oryd/kratos:latest-sqlite
    environment:
      - DSN=sqlite:///var/lib/sqlite/db.sqlite?_fk=true&mode=rwc
    volumes:
      - kratos-sqlite:/var/lib/sqlite
      - ./.kratos:/etc/config/kratos
    command: -c /etc/config/kratos/.kratos.yml migrate sql -e --yes
    restart: on-failure
    networks:
      - intranet
  kratos:
    depends_on:
      - kratos-migrate
    image: oryd/kratos:latest-sqlite
    ports:
      - 4433:4433 # public
      - 4434:4434 # admin
    restart: unless-stopped
    environment:
      - DSN=sqlite:///var/lib/sqlite/db.sqlite?_fk=true
    command: serve -c /etc/config/kratos/.kratos.yml --dev
    volumes:
      - kratos-sqlite:/var/lib/sqlite
      - ./.kratos:/etc/config/kratos
    networks:
      - intranet
  hydra:
    image: oryd/hydra
    ports:
      - 4444:4444 # Public port
      - 4445:4445 # Admin port
      - 5555:5555 # Port for hydra token user
    command: serve all --dangerous-force-http
    volumes:
      - ./.hydra/.hydra.yml:/.hydra
    restart: unless-stopped
    networks:
      - intranet
  nginx:
    image: nginx
    depends_on:
      - kratos
    ports:
      - 4455:4455
      - 4456:4456
    restart: on-failure
    network_mode: host
    volumes:
      - ./.nginx/nginx.linux.conf:/etc/nginx/conf.d/default.conf
  mailslurper:
    image: oryd/mailslurper:latest-smtps
    ports:
      - 4436:4436
      - 4437:4437
    networks:
      - intranet
networks:
  intranet:
volumes:
  kratos-sqlite:
